[features]
seeds = false
skip-lint = false
[programs.localnet]
myepicproject = "6cFQPTmKF8vzYu1v8Gktj3JAVz6C5EnhBDztEzXPqGEM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/niemawidaha/.config/solana/id.json"

[scripts]
test = "node tests/sceneportal.js"

